version: '3.8'

volumes:
  datafiles:

services:
  website:
    container_name: erms-website
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:80
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.0
    container_name: mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_TCP_PORT=3306
    volumes:
      - datafiles:/var/lib/mysql
    restart: always

    
    